runtime: python313

entrypoint: gunicorn -b :$PORT orders_sms_service.wsgi:application # Run gunicorn on GAE’s $PORT

runtime_config:
  runtime_version: 3.13.7

# env vars are in GitHub secrets for security

# Handlers serve static files via whitenoise and ensures HTTPS.
handlers:
- url: /static
  static_dir: staticfiles
  expiration: 1d
- url: /.*
  script: auto
  secure: always

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2
  