# Generated by Django 5.2.6 on 2025-09-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
