# Generated by Django 5.2.6 on 2025-09-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_mgmt', '0002_rename_customers_customer_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Item',
            new_name='item',
        ),
    ]
