# Generated by Django 5.2.6 on 2025-10-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_mgmt', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_mgmt.customer'),
        ),
    ]
